language: node_js
node_js:
 - "node"
 before_install:
 - npm install -g typescript
install:
   - npm i
script:
   - npm t
after_script: "cat test/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"